import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { importCharacterDocument, createTypeSScoutReserveShipForCharacter, createShipCombatEncounter, advanceShipCombatPhase, createSequenceDice } from '../index.js';
import {enableVectorMovement,previewShipVector,commitShipVector,vectorRangeDM} from '../src/starships/vector-movement.js';
function fixture(){const ch=importCharacterDocument(JSON.parse(readFileSync(new URL('./fixtures/Hawkeye-v0.6.character.json',import.meta.url))));const {ship}=createTypeSScoutReserveShipForCharacter(ch);return enableVectorMovement(createShipCombatEncounter({id:'vector',participants:['intruder','native'].map(side=>({shipId:side,side,ship,carriedPrograms:['maneuver'],loadedPrograms:['maneuver']}))}),{intruder:{position:{x:0,y:0},velocity:{x:3,y:0}},native:{position:{x:151,y:0},velocity:{x:0,y:0}}});}
test('1 G adds two thousand miles per turn; no thrust retains velocity',()=>{let e=fixture();assert.deepEqual(previewShipVector(e,'intruder',{x:2,y:0}).endpoint,{x:5,y:0});e=commitShipVector(e,'intruder',{x:0,y:0},createSequenceDice([6,6]));assert.equal(e.spatial.ships.intruder.position.x,3);assert.throws(()=>commitShipVector(e,'intruder',{x:0,y:0},createSequenceDice([6,6])),/already/);});
test('wrong side, phase and over-thrust are refused',()=>{const e=fixture();assert.throws(()=>commitShipVector(e,'native',{x:0,y:0},createSequenceDice([6,6])),/phase/);assert.throws(()=>previewShipVector(e,'intruder',{x:5,y:0}),/exceeds/);assert.throws(()=>commitShipVector(advanceShipCombatPhase(e),'intruder',{x:0,y:0},createSequenceDice([6,6])),/phase/);});
test('range boundaries use strict greater-than and state round-trips',()=>{const e=fixture();assert.equal(vectorRangeDM(e,'intruder','native').dm,-2);e.spatial.ships.native.position.x=150;assert.equal(vectorRangeDM(e,'intruder','native').dm,0);e.spatial.ships.native.position.x=301;assert.equal(vectorRangeDM(e,'intruder','native').dm,-5);assert.deepEqual(JSON.parse(JSON.stringify(e)),e);});
test('failed computer coasts and commits once',()=>{const e=fixture();e.participants[0].ship.state.damage.computer=12;const n=commitShipVector(e,'intruder',{x:2,y:0},createSequenceDice([6,6]));assert.equal(n.spatial.ships.intruder.position.x,3);});
