#!/usr/bin/env node
// cache-stamp.mjs v1.1.1 — 2026-07-10
// v1.1.1: reject the `release X.Y.Z` typo (missing --) instead of silently
//   consuming it as filenames and stamping nothing.
// v1.1.0: platform version manifest. Besides stamping ?v= content hashes,
//   scrapes each local js file's header line (// <name> vX.Y.Z) and writes
//   gcc-version.js: window.GCC_VERSION = { platform, date, modules } plus a
//   small on-page badge (bottom-left "GCC vX.Y.Z", click to list module
//   versions — the bug-report screenshot). Platform version comes from
//   --release X.Y.Z and persists in the manifest across plain runs; module
//   entries for files absent from the current slice are preserved. The
//   manifest is written BEFORE hashing so its own ?v= stamp is correct.
//   Workflow: node cache-stamp.mjs --release 0.27.32 && git tag v0.27.32
// v1.0.0: Node port of cache-stamp.py (same behavior, no dependencies).
//   node cache-stamp.mjs                              # stamp all *.html here
//   node cache-stamp.mjs index.html character.html    # stamp specific files
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';

const INCLUDE_RE = /(<(?:script|link)\b[^>]*?\b(?:src|href)=")([^"?#>]+\.(?:js|css))((?:\?[^"#>]*)?)("[^>]*>)/gi;
const HEADER_VER_RE = /^\/\/\s*([\w.-]+\.(?:js|mjs|css))\s+v(\d+\.\d+\.\d+[\w.-]*)/;
const MANIFEST = 'gcc-version.js';

function shortHash(path){
  return createHash('md5').update(readFileSync(path)).digest('hex').slice(0, 8);
}

function readManifest(){
  try {
    const src = readFileSync(MANIFEST, 'utf8');
    const m = src.match(/window\.GCC_VERSION\s*=\s*(\{[\s\S]*?\});/);
    if (m) return JSON.parse(m[1].replace(/'/g, '"'));
  } catch (err){ /* first run */ }
  return { platform:'0.0.0', date:'', modules:{} };
}

function scrapeModuleVersions(prev){
  const modules = { ...prev };
  for (const f of readdirSync('.')){
    if (!/\.(js|mjs)$/.test(f) || f === MANIFEST) continue;
    try {
      const firstLine = readFileSync(f, 'utf8').split('\n', 1)[0];
      const m = firstLine.match(HEADER_VER_RE);
      if (m) modules[m[1].replace(/\.(js|mjs)$/, '')] = m[2];
    } catch (err){ /* unreadable — keep prior entry */ }
  }
  return modules;
}

function writeManifest(platform, modules){
  const date = new Date().toISOString().slice(0, 10);
  const data = JSON.stringify({ platform, date, modules }, null, 2);
  const body = `// ${MANIFEST} — GENERATED by cache-stamp.mjs v1.1.1. Do not edit by hand.
// Regenerate: node cache-stamp.mjs [--release X.Y.Z]
window.GCC_VERSION = ${data};
// On-page version badge. Opt out per page with <body data-no-version-badge>.
(function(){
  if (typeof document === 'undefined') return;
  function mount(){
    if (document.body?.dataset?.noVersionBadge !== undefined) return;
    if (document.getElementById('gcc-version-badge')) return;
    var v = window.GCC_VERSION;
    var b = document.createElement('div');
    b.id = 'gcc-version-badge';
    b.style.cssText = 'position:fixed;left:8px;bottom:6px;z-index:9999;font:10px/1.4 monospace;color:#8b6e45;background:rgba(0,0,0,.35);padding:1px 7px;border-radius:8px;cursor:pointer;user-select:none;opacity:.75';
    b.textContent = 'GCC v' + v.platform;
    b.title = 'Click for module versions (' + v.date + ')';
    var pop = null;
    b.onclick = function(){
      if (pop){ pop.remove(); pop = null; return; }
      pop = document.createElement('div');
      pop.style.cssText = 'position:fixed;left:8px;bottom:26px;z-index:9999;font:10px/1.5 monospace;color:#c8a96e;background:rgba(10,8,4,.95);border:1px solid #4a3518;border-radius:6px;padding:6px 10px;max-height:50vh;overflow-y:auto';
      var rows = Object.keys(v.modules).sort().map(function(k){ return k + ' v' + v.modules[k]; });
      pop.textContent = 'GCC platform v' + v.platform + ' (' + v.date + ')\\n' + rows.join('\\n');
      pop.style.whiteSpace = 'pre';
      document.body.appendChild(pop);
    };
    document.body.appendChild(b);
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mount);
  else mount();
})();
`;
  writeFileSync(MANIFEST, body, 'utf8');
}

function stampFile(htmlPath){
  const base = dirname(resolve(htmlPath));
  const src = readFileSync(htmlPath, 'utf8');
  let changed = 0;

  const out = src.replace(INCLUDE_RE, (m, pre, asset, _oldq, post) => {
    if (asset.includes('://') || asset.startsWith('//')) return m;
    const target = join(base, asset);
    if (!existsSync(target) || !statSync(target).isFile()) return m;
    changed++;
    return pre + asset + '?v=' + shortHash(target) + post;
  });

  if (out !== src) writeFileSync(htmlPath, out, 'utf8');
  return changed;
}

const args = process.argv.slice(2);
let release = null;
const relIdx = args.indexOf('--release');
if (relIdx !== -1){
  release = args[relIdx + 1];
  if (!/^\d+\.\d+\.\d+/.test(release || '')){ console.error('--release expects X.Y.Z'); process.exit(1); }
  args.splice(relIdx, 2);
}
// Catch the easy typo: `release 0.27.32` (missing --) would otherwise be
// consumed as HTML filenames and silently stamp nothing.
const typo = args.find(a => a === 'release' || /^\d+\.\d+\.\d+$/.test(a));
if (typo){
  console.error(`error: '${typo}' looks like a release argument — did you mean:  node cache-stamp.mjs --release ${args.find(a => /^\d+\.\d+\.\d+$/.test(a)) || 'X.Y.Z'}`);
  process.exit(1);
}

const prev = readManifest();
const platform = release || prev.platform;
writeManifest(platform, scrapeModuleVersions(prev.modules || {}));
console.log(`${MANIFEST}: platform v${platform}${release ? ' (new release)' : ''}`);

const files = args.length
  ? args
  : readdirSync('.').filter(f => f.toLowerCase().endsWith('.html'));

if (!files.length){
  console.log('cache-stamp: no HTML files found.');
  process.exit(1);
}
let total = 0;
for (const f of files){
  if (!existsSync(f)){ console.log(`skip (not found): ${f}`); continue; }
  const n = stampFile(f);
  total += n;
  console.log(`${f}: stamped ${n} include${n === 1 ? '' : 's'}`);
}
console.log(`done — ${total} include${total === 1 ? '' : 's'} across ${files.length} file${files.length === 1 ? '' : 's'}`);
