// gcc-version.js — GENERATED by cache-stamp.mjs v1.1.0. Do not edit by hand.
// Regenerate: node cache-stamp.mjs [--release X.Y.Z]
window.GCC_VERSION = {
  "platform": "0.27.32",
  "date": "2026-07-10",
  "modules": {
    "gcc-map-parent-renderer": "1.1.0",
    "gcc-terrain": "0.1.0",
    "gcc-voyage-cargo": "0.2.0",
    "gcc-voyage-finance": "0.2.2",
    "gcc-voyage": "0.13.0",
    "gcc-weather": "0.2.1"
  }
};
// On-page version badge. Opt out per page with <body data-no-version-badge>.
(function(){
  if (typeof document === 'undefined') return;
  function mount(){
    if (document.body?.dataset?.noVersionBadge !== undefined) return;
    if (document.getElementById('gcc-version-badge')) return;
    var v = window.GCC_VERSION;
    var b = document.createElement('div');
    b.id = 'gcc-version-badge';
    b.style.cssText = 'position:fixed;left:8px;bottom:6px;z-index:9999;font:10px/1.4 monospace;color:#8b6e45;background:rgba(0,0,0,.35);padding:1px 7px;border-radius:8px;cursor:pointer;user-select:none;opacity:.75';
    b.textContent = 'GCC v' + v.platform;
    b.title = 'Click for module versions (' + v.date + ')';
    var pop = null;
    b.onclick = function(){
      if (pop){ pop.remove(); pop = null; return; }
      pop = document.createElement('div');
      pop.style.cssText = 'position:fixed;left:8px;bottom:26px;z-index:9999;font:10px/1.5 monospace;color:#c8a96e;background:rgba(10,8,4,.95);border:1px solid #4a3518;border-radius:6px;padding:6px 10px;max-height:50vh;overflow-y:auto';
      var rows = Object.keys(v.modules).sort().map(function(k){ return k + ' v' + v.modules[k]; });
      pop.textContent = 'GCC platform v' + v.platform + ' (' + v.date + ')\n' + rows.join('\n');
      pop.style.whiteSpace = 'pre';
      document.body.appendChild(pop);
    };
    document.body.appendChild(b);
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mount);
  else mount();
})();
