// gcc-version.js — GENERATED by cache-stamp.mjs v1.1.1. Do not edit by hand.
// Regenerate: node cache-stamp.mjs [--release X.Y.Z]
window.GCC_VERSION = {
  "platform": "0.27.33",
  "date": "2026-07-10",
  "modules": {
    "gcc-map-parent-renderer": "1.1.0",
    "gcc-terrain": "0.1.0",
    "gcc-voyage-cargo": "0.2.0",
    "gcc-voyage-finance": "0.2.2",
    "gcc-voyage": "0.13.0",
    "gcc-weather": "0.2.1",
    "adnd-chargen": "1.2.0",
    "adnd-class-data": "1.2.0",
    "adnd-equipment": "6.0.0",
    "adnd-purse": "1.0.0",
    "gcc-auth": "1.0.0",
    "gcc-backup": "1.2.0",
    "gcc-coast-scanner": "0.4.6",
    "gcc-combat": "0.2.1",
    "gcc-data": "1.4.0",
    "gcc-edge-flags": "0.1.0",
    "gcc-edge-modes": "0.3.0",
    "gcc-edge-scanner": "0.5.5",
    "gcc-edges": "0.4.2",
    "gcc-encounters": "2.0.0",
    "gcc-finance": "0.3.0",
    "gcc-fog": "0.3.0",
    "gcc-header": "2.1.0",
    "gcc-hex-edit": "1.0.0",
    "gcc-images": "1.1.1",
    "gcc-invite": "1.0.0",
    "gcc-landmarks": "0.7.3",
    "gcc-lost": "0.1.0",
    "gcc-map-mile-renderer": "1.1.0",
    "gcc-map-subhex-palette": "1.4.1",
    "gcc-map-subhex-renderer": "1.5.0",
    "gcc-map": "0.2.4",
    "gcc-no-context-menu": "1.0.0",
    "gcc-paths": "0.10.1",
    "gcc-publish": "0.4.0",
    "gcc-pull": "0.2.2",
    "gcc-regions": "0.3.0",
    "gcc-rng": "0.1.0",
    "gcc-settings": "0.2.1",
    "gcc-storage": "1.0.0",
    "gcc-subhex-data": "2.12.0",
    "gcc-subhex-icons": "1.0.0",
    "gcc-subhex-paths": "2.4.0",
    "gcc-subhex-store": "0.4.0",
    "gcc-subhex-view": "3.2.0",
    "gcc-sync": "2.3.3",
    "gcc-table-feed": "0.1.1",
    "gcc-version-badge": "1.0.0",
    "gcc-voyage-trade": "0.1.1",
    "gw-annotations": "0.6.0",
    "gw-character-data": "0.1.0",
    "gw-cryptic-alliances": "0.1.0",
    "gw-data-v2": "2.0.1",
    "gw-encounter-data": "0.4.0",
    "gw-feature-gen": "0.7.0",
    "gw-flavor-tables": "0.1.1",
    "gw-map-sync": "0.1.1",
    "gw-mp-animal": "1.0.0",
    "gw-mp-bestiary": "0.2.0",
    "gw-mp-export": "0.2.0",
    "gw-mp-roles": "0.1.0",
    "gw-mp-weaknesses": "1.0.2",
    "gw-roll-tables": "0.1.0",
    "gw-stock": "0.2.0",
    "gw-subhex-atlas": "0.1.1",
    "gw-subhex-data": "0.6.0",
    "gw-subhex-tile-renderer": "0.1.5",
    "gw-subhex-view": "0.46.2",
    "gw-warheroes": "0.1.0",
    "mp-app": "4.13.3",
    "mp-canvas": "3.1.0",
    "mp-data": "2.6.0",
    "mp-vehicle": "3.3.0"
  }
};
// On-page version badge. Opt out per page with <body data-no-version-badge>.
(function(){
  if (typeof document === 'undefined') return;
  function mount(){
    if (document.body?.dataset?.noVersionBadge !== undefined) return;
    if (document.getElementById('gcc-version-badge')) return;
    var v = window.GCC_VERSION;
    var b = document.createElement('div');
    b.id = 'gcc-version-badge';
    b.style.cssText = 'position:fixed;left:8px;bottom:6px;z-index:9999;font:10px/1.4 monospace;color:#8b6e45;background:rgba(0,0,0,.35);padding:1px 7px;border-radius:8px;cursor:pointer;user-select:none;opacity:.75';
    b.textContent = 'GCC v' + v.platform;
    b.title = 'Click for module versions (' + v.date + ')';
    var pop = null;
    b.onclick = function(){
      if (pop){ pop.remove(); pop = null; return; }
      pop = document.createElement('div');
      pop.style.cssText = 'position:fixed;left:8px;bottom:26px;z-index:9999;font:10px/1.5 monospace;color:#c8a96e;background:rgba(10,8,4,.95);border:1px solid #4a3518;border-radius:6px;padding:6px 10px;max-height:50vh;overflow-y:auto';
      var rows = Object.keys(v.modules).sort().map(function(k){ return k + ' v' + v.modules[k]; });
      pop.textContent = 'GCC platform v' + v.platform + ' (' + v.date + ')\n' + rows.join('\n');
      pop.style.whiteSpace = 'pre';
      document.body.appendChild(pop);
    };
    document.body.appendChild(b);
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mount);
  else mount();
})();
